"""Machine-readable, non-self-congratulatory reproducibility assessments.

The assessment deliberately distinguishes structural evidence generated by the project
from independent reproduction, external scientific validation, legal review, and
empirical replication.  Passing local checks is never represented as external approval.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import urlparse

from rareburden.provenance import content_id


class ReproducibilityAssessmentError(ValueError):
    """Raised when a reproducibility assessment would be incomplete or misleading."""


_LEVEL_ORDER = {
    "R0_conceptual": 0,
    "R1_rerunnable": 1,
    "R2_auditable": 2,
    "R3_independently_reproduced": 3,
    "R4_externally_replicated": 4,
}
_ALLOWED_STATUS = {"met", "partially_met", "not_met", "not_applicable"}


def _criterion(
    *,
    criterion_id: str,
    title: str,
    status: str,
    evidence: Sequence[str],
    rationale: str,
    independently_verified: bool = False,
) -> dict[str, Any]:
    if status not in _ALLOWED_STATUS:
        raise ReproducibilityAssessmentError(f"Unsupported criterion status: {status}")
    cleaned_evidence = sorted({str(item).strip() for item in evidence if str(item).strip()})
    if status == "met" and not cleaned_evidence:
        raise ReproducibilityAssessmentError(
            f"Met criterion {criterion_id} requires machine-inspectable evidence"
        )
    if independently_verified and status != "met":
        raise ReproducibilityAssessmentError(
            f"Criterion {criterion_id} cannot be independently verified unless met"
        )
    return {
        "criterion_id": criterion_id,
        "title": title,
        "status": status,
        "evidence": cleaned_evidence,
        "rationale": rationale,
        "independently_verified": independently_verified,
    }


def build_reproducibility_assessment(
    *,
    release_id: str,
    workflow_run_id: str,
    created_at: str,
    criteria: Sequence[Mapping[str, Any]],
    claimed_level: str,
    limitations: Sequence[str],
) -> dict[str, Any]:
    """Build a content-addressed assessment with conservative level gating."""
    if claimed_level not in _LEVEL_ORDER:
        raise ReproducibilityAssessmentError(f"Unsupported reproducibility level: {claimed_level}")
    records: list[dict[str, Any]] = []
    seen: set[str] = set()
    for raw in criteria:
        identifier = str(raw.get("criterion_id", "")).strip()
        if not identifier or identifier in seen:
            raise ReproducibilityAssessmentError(
                "Reproducibility criterion identifiers must be unique and non-empty"
            )
        seen.add(identifier)
        records.append(
            _criterion(
                criterion_id=identifier,
                title=str(raw.get("title", "")).strip(),
                status=str(raw.get("status", "")).strip(),
                evidence=[str(item) for item in raw.get("evidence", [])],
                rationale=str(raw.get("rationale", "")).strip(),
                independently_verified=bool(raw.get("independently_verified", False)),
            )
        )
    if not records:
        raise ReproducibilityAssessmentError("At least one reproducibility criterion is required")
    records.sort(key=lambda item: str(item["criterion_id"]))
    by_id = {str(item["criterion_id"]): item for item in records}
    required_for_level = {
        "R1_rerunnable": {
            "source_identity",
            "software_identity",
            "environment_identity",
            "deterministic_execution",
        },
        "R2_auditable": {
            "prospective_protocol",
            "decision_and_deviation_log",
            "activity_level_provenance",
            "lineage_closure",
            "research_object",
            "reporting_evidence",
        },
        "R3_independently_reproduced": {"independent_reproduction"},
        "R4_externally_replicated": {"external_replication"},
    }
    for level, position in _LEVEL_ORDER.items():
        if position == 0 or position > _LEVEL_ORDER[claimed_level]:
            continue
        for required in required_for_level.get(level, set()):
            record = by_id.get(required)
            if record is None or record["status"] != "met":
                raise ReproducibilityAssessmentError(
                    f"Claimed level {claimed_level} requires met criterion {required}"
                )
            if (
                level in {"R3_independently_reproduced", "R4_externally_replicated"}
                and not record["independently_verified"]
            ):
                raise ReproducibilityAssessmentError(
                    "Claimed level "
                    f"{claimed_level} requires independent verification for {required}"
                )
    summary = {
        status: sum(item["status"] == status for item in records)
        for status in sorted(_ALLOWED_STATUS)
    }
    core = {
        "release_id": release_id,
        "workflow_run_id": workflow_run_id,
        "created_at": created_at,
        "assessment_method": "automated_internal_structural_assessment",
        "claimed_level": claimed_level,
        "criteria": records,
        "summary": summary,
        "limitations": sorted({str(item).strip() for item in limitations if str(item).strip()}),
        "external_approval_claimed": False,
    }
    return {
        "schema_version": "1.0.0",
        "reproducibility_assessment_id": content_id("repro", core),
        **core,
    }


def reference_assessment_criteria() -> list[dict[str, Any]]:
    """Return the conservative criteria used by the synthetic reference workflow."""
    return [
        {
            "criterion_id": "source_identity",
            "title": "Every input is snapshotted and content-addressed",
            "status": "met",
            "evidence": [
                "materials/source/",
                "acquisition/",
                "release-manifest.json",
            ],
            "rationale": "Synthetic inputs, acquisition records, and release hashes are included.",
        },
        {
            "criterion_id": "software_identity",
            "title": "Executed software is identified and archived",
            "status": "met",
            "evidence": [
                "materials/software/rareburden-source-snapshot.zip",
                "provenance/runs/",
            ],
            "rationale": "Run records capture version and Git state; source is included.",
        },
        {
            "criterion_id": "environment_identity",
            "title": "Execution environment and dependency lock are recorded",
            "status": "met",
            "evidence": ["materials/environment/pyproject.toml", "materials/environment/uv.lock"],
            "rationale": "Interpreter, platform, and lockfile identities are recorded.",
        },
        {
            "criterion_id": "deterministic_execution",
            "title": "Randomness and deterministic serialization are explicit",
            "status": "met",
            "evidence": ["analysis/expected-population-synthetic.json", "provenance/runs/"],
            "rationale": (
                "The random engine, version, seed, and canonical output formats are recorded."
            ),
        },
        {
            "criterion_id": "prospective_protocol",
            "title": "Prospective protocol status is explicit",
            "status": "met",
            "evidence": ["materials/protocols/protocol-registration.json"],
            "rationale": "Internal freeze is distinguished from external preregistration.",
        },
        {
            "criterion_id": "decision_and_deviation_log",
            "title": "Analytic choices and deviations are timing classified",
            "status": "met",
            "evidence": ["analysis/analysis-decision-log.json"],
            "rationale": "Prospective, implementation, and post-hoc choices are distinguishable.",
        },
        {
            "criterion_id": "activity_level_provenance",
            "title": "Each transformation has immutable activity-level provenance",
            "status": "met",
            "evidence": [
                "provenance/runs/",
                "provenance/workflow-run.json",
                "provenance/prov.jsonld",
            ],
            "rationale": "Native records and an interoperable W3C PROV-O projection are included.",
        },
        {
            "criterion_id": "lineage_closure",
            "title": "Lineage is closed from entry inputs to final outputs",
            "status": "met",
            "evidence": ["provenance/lineage-audit.json"],
            "rationale": "Producer-consumer identities and source acquisition links are audited.",
        },
        {
            "criterion_id": "research_object",
            "title": "A self-contained workflow research object is present",
            "status": "met",
            "evidence": ["ro-crate-metadata.json"],
            "rationale": "The release is described as an RO-Crate and Process Run Crate.",
        },
        {
            "criterion_id": "reporting_evidence",
            "title": "Health-estimate reporting requirements are mapped to evidence",
            "status": "met",
            "evidence": ["reports/gather-checklist.json"],
            "rationale": (
                "Every GATHER item is represented with evidence or a transparent limitation."
            ),
        },
        {
            "criterion_id": "independent_reproduction",
            "title": "A separate operator has reproduced the release",
            "status": "not_met",
            "evidence": [],
            "rationale": (
                "No independent operator or environment has yet reproduced this candidate."
            ),
            "independently_verified": False,
        },
        {
            "criterion_id": "external_replication",
            "title": "The method has been replicated on an external empirical dataset",
            "status": "not_met",
            "evidence": [],
            "rationale": "The reference workflow uses only synthetic data.",
            "independently_verified": False,
        },
    ]


def _safe_evidence_path(root: Path, value: str) -> Path:
    path = PurePosixPath(value.removesuffix("/"))
    if not value or path.is_absolute() or ".." in path.parts or "\\" in value:
        raise ReproducibilityAssessmentError(
            f"Unsafe reproducibility evidence path: {value!r}"
        )
    root_resolved = root.expanduser().resolve()
    candidate = root_resolved / path.as_posix()
    try:
        candidate.resolve().relative_to(root_resolved)
    except ValueError as exc:
        raise ReproducibilityAssessmentError(
            f"Reproducibility evidence escapes package root: {value}"
        ) from exc
    return candidate


def verify_reproducibility_assessment(
    assessment: Mapping[str, Any],
    *,
    root: Path | None = None,
    expected_release_id: str | None = None,
    expected_workflow_run_id: str | None = None,
) -> list[str]:
    """Verify assessment identity, level gates, and locally asserted evidence."""
    failures: list[str] = []
    core = {
        key: value
        for key, value in assessment.items()
        if key not in {"schema_version", "reproducibility_assessment_id"}
    }
    try:
        expected_identifier = content_id("repro", core)
    except Exception as exc:
        failures.append(f"unable to recompute reproducibility assessment identifier: {exc}")
    else:
        if assessment.get("reproducibility_assessment_id") != expected_identifier:
            failures.append("reproducibility assessment content identifier mismatch")

    if expected_release_id is not None and assessment.get("release_id") != expected_release_id:
        failures.append("reproducibility assessment refers to the wrong release")
    if (
        expected_workflow_run_id is not None
        and assessment.get("workflow_run_id") != expected_workflow_run_id
    ):
        failures.append("reproducibility assessment refers to the wrong workflow run")
    if assessment.get("external_approval_claimed") is not False:
        failures.append("internal assessment must not claim external approval")

    criteria = assessment.get("criteria")
    if not isinstance(criteria, list):
        return [*failures, "reproducibility criteria must be a list"]
    try:
        rebuilt = build_reproducibility_assessment(
            release_id=str(assessment.get("release_id", "")),
            workflow_run_id=str(assessment.get("workflow_run_id", "")),
            created_at=str(assessment.get("created_at", "")),
            criteria=[item for item in criteria if isinstance(item, Mapping)],
            claimed_level=str(assessment.get("claimed_level", "")),
            limitations=[str(item) for item in assessment.get("limitations", [])],
        )
    except (TypeError, ReproducibilityAssessmentError) as exc:
        failures.append(f"reproducibility level gate failed: {exc}")
    else:
        if rebuilt != dict(assessment):
            failures.append("reproducibility assessment differs from canonical rebuild")

    if root is None:
        return sorted(set(failures))
    for criterion in criteria:
        if not isinstance(criterion, Mapping) or criterion.get("status") != "met":
            continue
        for evidence in criterion.get("evidence", []):
            value = str(evidence)
            parsed = urlparse(value)
            if parsed.scheme:
                if parsed.scheme != "https" or not parsed.netloc:
                    failures.append(f"unsupported external evidence identifier: {value}")
                continue
            try:
                path = _safe_evidence_path(root, value)
            except ReproducibilityAssessmentError as exc:
                failures.append(str(exc))
                continue
            if value.endswith("/"):
                if path.is_symlink() or not path.is_dir() or not any(path.iterdir()):
                    failures.append(f"evidence directory is missing or empty: {value}")
            elif path.is_symlink() or not path.is_file():
                failures.append(f"evidence file is missing or unsafe: {value}")
    return sorted(set(failures))


__all__ = [
    "ReproducibilityAssessmentError",
    "build_reproducibility_assessment",
    "reference_assessment_criteria",
    "verify_reproducibility_assessment",
]
